# Stage 5: HTML and Markdown output from a valid candidate profile

PROFILE_TITLES = {
    "FULL_STACK_DEVELOPER": "Full Stack Developer",
    "MACHINE_LEARNING_ENGINEER": "Machine Learning Engineer",
    "DEVOPS_ENGINEER": "DevOps Engineer",
    "DATA_ANALYST": "Data Analyst",
}

STYLE = """
        body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 40px; }
        .candidate-card { max-width: 850px; margin: auto; background-color: white;
                          border: 1px solid #cccccc; border-radius: 10px; padding: 30px; }
        .header { border-bottom: 2px solid #333333; margin-bottom: 25px; }
        .header h1 { margin-bottom: 5px; }
        .header p { margin-top: 0; }
        .section { margin-bottom: 25px; }
        .section h2 { border-bottom: 1px solid #dddddd; padding-bottom: 5px; }
        .skills { display: flex; flex-wrap: wrap; gap: 10px; }
        .skill { background-color: #eeeeee; border-radius: 5px; padding: 8px 12px; }
        .evaluation { background-color: #eeeeee; padding: 20px; border-radius: 8px; margin-bottom: 10px; }
        .accepted { font-weight: bold; color: #1a7f37; }
        .rejected { color: #8a8a8a; }
        .metadata { font-size: 0.9em; }
"""


def escape(text):
    # basic HTML escape
    text = str(text)
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return text.replace('"', "&quot;")


def profile_title(name):
    return PROFILE_TITLES.get(name, name)


def to_html(model):
    # model is a valid CandidateProfile from textX
    h = []
    h.append("<!DOCTYPE html>")
    h.append('<html lang="en">')
    h.append("<head>")
    h.append('    <meta charset="UTF-8">')
    h.append('    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
    h.append("    <title>ResumeLens - " + escape(model.name) + "</title>")
    h.append("    <style>" + STYLE + "    </style>")
    h.append("</head>")
    h.append("<body>")
    h.append('<div class="candidate-card">')

    # header
    h.append('    <div class="header">')
    h.append("        <h1>" + escape(model.name) + "</h1>")
    h.append("        <p>Candidate Profile generated by ResumeLens</p>")
    h.append("    </div>")

    # personal information
    h.append('    <div class="section">')
    h.append("        <h2>Personal Information</h2>")
    h.append("        <p><strong>Email:</strong> " + escape(model.contact.email) + "</p>")
    if model.contact.phone:
        h.append("        <p><strong>Phone:</strong> " + escape(model.contact.phone) + "</p>")
    if model.contact.location:
        h.append("        <p><strong>Location:</strong> " + escape(model.contact.location) + "</p>")
    h.append("    </div>")

    if model.summary:
        h.append('    <div class="section">')
        h.append("        <h2>Profile Summary</h2>")
        h.append("        <p>" + escape(model.summary) + "</p>")
        h.append("    </div>")

    if model.experience:
        h.append('    <div class="section">')
        h.append("        <h2>Experience</h2>")
        for job in model.experience.jobs:
            years = str(job.years) + (" year" if job.years == 1 else " years")
            h.append("        <h3>" + escape(job.role) + "</h3>")
            h.append('        <p class="metadata">' + escape(job.company) + " &middot; " + years + "</p>")
        h.append("    </div>")

    if model.education:
        h.append('    <div class="section">')
        h.append("        <h2>Education</h2>")
        h.append("        <ul>")
        for record in model.education.records:
            h.append("            <li>" + escape(record.title) + " &ndash; " + escape(record.institution) + "</li>")
        h.append("        </ul>")
        h.append("    </div>")

    # skills after FST normalization
    h.append('    <div class="section">')
    h.append("        <h2>Normalized Technical Skills</h2>")
    h.append('        <div class="skills">')
    if model.skills.names:
        for skill in model.skills.names:
            h.append('            <span class="skill">' + escape(skill) + "</span>")
    else:
        h.append("            <p>No skills recognized.</p>")
    h.append("        </div>")
    h.append("    </div>")

    # results of the automata
    h.append('    <div class="section">')
    h.append("        <h2>Qualification Evaluation</h2>")
    for result in model.evaluation.results:
        css = "accepted" if result.status == "ACCEPTED" else "rejected"
        h.append('        <div class="evaluation">')
        h.append("            <p><strong>Profile evaluated:</strong> " + profile_title(result.profile) + "</p>")
        h.append('            <p><strong>Qualification pattern:</strong> <span class="' + css + '">'
                 + result.status + "</span></p>")
        if result.status == "ACCEPTED":
            h.append("            <p>The normalized qualifications satisfy an accepted "
                     + profile_title(result.profile) + " pattern.</p>")
        h.append("        </div>")
    h.append("    </div>")

    h.append("</div>")
    h.append("</body>")
    h.append("</html>")
    return "\n".join(h) + "\n"


def to_markdown(model):
    m = []
    m.append("# " + model.name)
    m.append("")
    m.append("*Candidate Profile generated by ResumeLens*")
    m.append("")
    m.append("## Personal Information")
    m.append("")
    m.append("- **Email:** " + model.contact.email)
    if model.contact.phone:
        m.append("- **Phone:** " + model.contact.phone)
    if model.contact.location:
        m.append("- **Location:** " + model.contact.location)
    m.append("")

    if model.summary:
        m.append("## Profile Summary")
        m.append("")
        m.append(model.summary)
        m.append("")

    if model.experience:
        m.append("## Experience")
        m.append("")
        for job in model.experience.jobs:
            m.append("- **" + job.role + "** - " + job.company + " (" + str(job.years) + " years)")
        m.append("")

    if model.education:
        m.append("## Education")
        m.append("")
        for record in model.education.records:
            m.append("- " + record.title + " - " + record.institution)
        m.append("")

    m.append("## Normalized Technical Skills")
    m.append("")
    if model.skills.names:
        m.append(" ".join("`" + s + "`" for s in model.skills.names))
    else:
        m.append("No skills recognized.")
    m.append("")

    m.append("## Qualification Evaluation")
    m.append("")
    m.append("| Profile | Result |")
    m.append("|---|---|")
    for result in model.evaluation.results:
        status = "**ACCEPTED**" if result.status == "ACCEPTED" else "REJECTED"
        m.append("| " + profile_title(result.profile) + " | " + status + " |")
    m.append("")
    return "\n".join(m)


def save(text, path):
    with open(path, "w", encoding="utf-8") as file:
        file.write(text)


if __name__ == "__main__":
    from src.profile_language import parse_profile
    with open("tests/profiles/wednesday_addams.cand", "r", encoding="utf-8") as file:
        profile = parse_profile(file.read())
    print(to_markdown(profile))
